title: Dima Altukhov
tagline: Senior DevOps & Cloud Engineer
logo: /assets/img/logo.jpeg
description: Senior DevOps Engineer with 20+ years of experience in Kubernetes, AWS, Service Mesh, and Infrastructure as Code. Expert Go/JS developer.
show_downloads: false
google_analytics: G-NWHFQ803VQ
theme: jekyll-theme-minimal

# SEO and Social Media
author: Dima Altukhov
url: "https://www.altuhov.su"
baseurl: ""
twitter_username: altuhov
github_username: alt-dima
linkedin_username: altuhov
